/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bird.glb -o src/components/models/Bird.tsx 
Author: zhao517578549 (https://sketchfab.com/zhao517578549)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bird-7a51fc9ea78d499e980a929ca25a6dba
Title: bird
*/
"use client";
import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFAction = THREE.AnimationClip;

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
  }
  materials: {
    lambert7SG: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/bird.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={0.01}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert7SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert7SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert7SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/bird.glb')
