/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cool_man.glb -o src/components/models/CoolMan.tsx 
Author: ardhanaputra (https://sketchfab.com/ardhanaputra)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cool-man-ad14b71697dd4ea7836c1f06c75e5f72
Title: Cool Man
*/
"use client";
import * as THREE from 'three'
import { useRef, useMemo, useState } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function CoolMan(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('models/cool_man.glb') as any
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { actions } = useAnimations(animations, group)

  const targetZ = 0  // The “current spot” Z position
  const speed = 2    // Forward speed
  const [hasArrived, setHasArrived] = useState(false)

  useFrame((state, delta) => {
    if (!group.current) return

    if (!hasArrived) {
      // Phase 1: move forward from back
      group.current.position.z += speed * delta

      if (group.current.position.z >= targetZ) {
        group.current.position.z = targetZ
        setHasArrived(true)
      }
    } else {
      // Phase 2: start revolving in place
      group.current.rotation.y += delta * 0.5

      // Optional: subtle forward/back sway
      group.current.position.z = targetZ + Math.sin(state.clock.getElapsedTime()) * 0.2
    }
  })

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[0, -2, -10]} // Start from far back on Z
      scale={[2, 2, 2]}
    >
      <primitive object={clone} />
    </group>
  )
}

useGLTF.preload('models/cool_man.glb')

